-- 1: Database Exploration
(
select * from information_schema.tables                   -- Retrieve a list of all tables in the database

select * from information_schema.columns                  -- Retrieve all columns for a specific table (dim_customers)
where table_name ='dim_customers'                           
)

-- 2: Dimensions Exploration

(
select distinct category,sub_category,product_name
from gold.dim_products                                     -- Retrieve a list of unique categories, subcategories, and products
order by 1,2,3

select distinct country 
from gold.dim_customers                                    -- Retrieve a list of unique countries from which customers originate
)

-- 3: Date Exploration

(
select min(birthdate) as oldest_birthdate,
		   timestampdiff(year,min(birthdate),current_timestamp) as oldest_age,
		   max(birthdate) as youngest_birthdate ,                                -- Find the youngest and oldest customer based on birthdate
	     timestampdiff(year,max(birthdate),current_timestamp) as youngest_age
from gold.dim_customers
        
select min(order_date) as first_date,
	     max(order_date) as last_date,                                          -- Determine the first and last order date and the total duration in months
       timestampdiff(month,min(order_date),max(order_date)) as order_range
from gold.fact_sales
)

-- 4: Measures Exploration

(
select 'Total sales' as measure_name,sum(sales_amount) as measure_value from gold.fact_sales 
union all
select 'Total Quantity' ,sum(sales_quantity)  from gold.fact_sales 
union all
select 'Average Price',avg(price)  from gold.fact_sales 
union all                                                                                 -- Generate a Report that shows all key metrics of the business
select'Total Orders', count(distinct order_number)  from gold.fact_sales 
union all
select 'Total Products',count(distinct product_name) from gold.dim_products
union all
select 'Total Customers',count(customer_key)  from gold.dim_customers
)

-- 5: Magnitude

(
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_customers as c           -- What is the total revenue generated by each customer?
on 	c.customer_key =f.customer_key
group by
f.customer_key,
c.first_name,
c.last_name
order by total_revenue DESC
)
(
select
    c.country,
    sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c              -- What is the distribution of sold items across countries?
    on c.customer_key = f.customer_key
group by c.country
order by total_sold_items DESC
)

-- 6: Ranking Top N - Bottom N

(
select 
    c.customer_key,
    c.first_name,
    c.last_name,
    sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c                -- Find the top 10 customers who have generated the highest revenue
    on c.customer_key = f.customer_key
group by
    c.customer_key,
    c.first_name,
    c.last_name
order by total_revenue DESC
limit 10
)
(
select 
    p.product_name,
    sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p                   -- What are the 5 worst-performing products in terms of sales?
    on p.product_key = f.product_key
group by p.product_name
order by total_revenue
limit 5
)
